#!/usr/bin/env bash
# brigade-launch-agent.sh — safe Claude launcher for brigade panes
#
# Generated by cli-forge-chef skill. Template — the skill writes this to
# {project}/scripts/brigade-launch-agent.sh at Phase 2.
#
# Usage:
#   brigade-launch-agent.sh <role> <session>
#
# Reads:
#   ${PROJECT_ROOT}/.claude/prompts/<role>-<session>.md           → --append-system-prompt
#   ${PROJECT_ROOT}/.claude/prompts/<role>-<session>.initial.txt  → initial user message (optional)
#
# Why this wrapper exists (G34):
#   `claude --append-system-prompt "$(cat prompt.md)"` in a tmuxinator YAML re-parses the
#   markdown through the shell. A prompt with 96 backticks + 106 quotes (real case) breaks
#   on command-substitution, unbalanced quotes, or embedded `$(...)`. Using `$(< file)` bypasses
#   the parser — the content becomes a single shell string, never re-interpreted.
#
# Why not `set -o pipefail` (G35):
#   Combined with `git ... | head -1` elsewhere in the pipeline, pipefail kills git via
#   SIGPIPE before it finishes. Here we don't pipe, but keeping `-eu` only is a safer habit
#   for bash 3.2 (macOS default).
#
# Why the conditional array expansion (G38):
#   On bash 3.2, `"${EXTRA_FLAGS[@]}"` with an empty array + `set -u` raises
#   "unbound variable". `${EXTRA_FLAGS[@]+"${EXTRA_FLAGS[@]}"}` expands the array only
#   if it is set, which is the portable safe pattern.

set -eu  # NOT pipefail — avoids SIGPIPE on downstream `| head` callers

ROLE="${1:?Usage: $0 <role> <session>}"
SESSION="${2:?Usage: $0 <role> <session>}"

# PROJECT_ROOT is injected by the tmuxinator `root:` directive (tmux sets cwd).
# Fall back to the script's parent-of-parent if run standalone.
PROJECT_ROOT="${PROJECT_ROOT:-$(cd "$(dirname "$0")/.." && pwd)}"

PROMPT_FILE="${PROJECT_ROOT}/.claude/prompts/${ROLE}-${SESSION}.md"
INITIAL_FILE="${PROJECT_ROOT}/.claude/prompts/${ROLE}-${SESSION}.initial.txt"

if [[ ! -f "${PROMPT_FILE}" ]]; then
  echo "ERROR: prompt file not found: ${PROMPT_FILE}" >&2
  exit 1
fi

# `$(< file)` reads the entire file as a single shell string, no re-parsing (G34).
PROMPT="$(< "${PROMPT_FILE}")"

if [[ -f "${INITIAL_FILE}" ]]; then
  INITIAL_MSG="$(< "${INITIAL_FILE}")"
else
  INITIAL_MSG="Begin now per the system prompt."
fi

# Roles that need to see / talk to teammates get --teammate-mode tmux (G4).
declare -a EXTRA_FLAGS=()
case "${ROLE}" in
  chef|sous-chef-merge|contre-chef-inter|inter)
    EXTRA_FLAGS+=("--teammate-mode" "tmux")
    ;;
esac

# Conditional array expansion — works on bash 3.2 with empty arrays under set -u (G38).
exec claude \
  --dangerously-skip-permissions \
  --permission-mode bypassPermissions \
  ${EXTRA_FLAGS[@]+"${EXTRA_FLAGS[@]}"} \
  --append-system-prompt "${PROMPT}" \
  "${INITIAL_MSG}"
